chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

intellbillgames_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views as v
from intellbillgames_webapp import settings
import inventory.views as i
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", v.index, name="index"),
    path("login", v.account_login, name="login"),
    path("logout", v.account_logout, name="logout"),
    path("signup", v.signup, name="signup"),
    path("shop", i.shop, name="shop"),
    path("order/", i.order_detail, name="order_detail"),
    path("add_to_order/<int:product_id>/", i.add_to_order, name="add_to_order"),
    path(
        "remove_from_order/<int:product_id>/",
        i.remove_from_order,
        name="remove_from_order",
    ),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
from accounts.models import Customer


class BaseProduct(models.Model):
    SUPPLIES = "S"
    SINGLES = "SC"
    OTHER = "O"
    SEALED_PRODUCT = "SP"

    CATEGORY_CHOICES = [
        (SUPPLIES, "Supplies"),
        (SINGLES, "Singles"),
        (OTHER, "Other"),
        (SEALED_PRODUCT, "Sealed product"),
    ]

    name = models.CharField(max_length=200)
    in_store = models.IntegerField()
    in_storage = models.IntegerField()
    in_collection = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    imagen = models.ImageField(upload_to="products/", null=True)


class Product(BaseProduct):
    detail = models.TextField()





class Order(models.Model):
    date = models.DateField(auto_now=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    products = models.ManyToManyField(BaseProduct, through="OrderDetail")
    status = models.CharField(max_length=2)

class OrderDetail(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(BaseProduct, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

inventory/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import BaseProduct
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import Product, Order, OrderDetail


def shop(request):
    product_list = BaseProduct.objects.all()
    paginator = Paginator(product_list, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "inventory/shop.html", {"page_obj": page_obj})


@login_required
def order_detail(request):
    order, created = Order.objects.get_or_create(customer=request.user.customer)
    return render(request, "inventory/order_detail.html", {"order": order})


@login_required
def add_to_order(request, product_id):
    product = get_object_or_404(BaseProduct, id=product_id)
    order, created = Order.objects.get_or_create(customer=request.user.customer)
    order_item, created = OrderDetail.objects.get_or_create(
        order=order, product=product, defaults={"quantity":1}
    )

    if not created:
        order_item.quantity += 1
        order_item.save()

    return redirect("order_detail")


@login_required
def remove_from_order(request, product_id):
    product = get_object_or_404(BaseProduct, id=product_id)
    order = get_object_or_404(Order, customer=request.user.customer)
    order_item = get_object_or_404(OrderDetail, order=order, product=product)
    order_item.delete()
    return redirect("order_detail")

inventory/templates/inventory/order_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>order</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .navbar {
            background-color: #37265d;
        }
        
        .navbar a {
            color: #f8f9fa;
        }

        .navbar-brand {
            color: #fff !important;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">Intell Bill Games</a>
        ss="navbar-brand" href="/">Intell Bill Games</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'order_detail' %}">Order</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'room' room_name='support' %}">Chat</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Your order</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Total</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.orderdetail_set.all %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>${{ item.product.price }}</td>
                    <td>${% widthratio item.product.price 1 item.quantity %}</td>
                    <td>
                        <a href="{% url 'remove_from_order' item.product.id %}" class="btn btn-danger btn-sm">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

inventory/templates/inventory/shop.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
        }

        .navbar {
            background-color: #37265d;
        }

        .navbar a {
            color: #f8f9fa;
        }

        .navbar-brand {
            color: #fff !important;
        }

        .card {
            margin-bottom: 20px;
        }

        .card-title {
            color: #37265d;
        }

        .card-text {
            color: #555;
        }

        .pagination {
            justify-content: center;
        }

        .card-img-top {
            object-fit: cover;
        }
        .banner {
            height: 400px;
            background-color: #f0f0f0;
            background-image: url("{% static 'images/img1.jpg' %}");
            background-size: cover;
            background-position: center;
            border-radius: 0 0 20px 20px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="/">Intell Bill Games</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'order_detail' %}">Order</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'room' room_name='support' %}">Chat</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="banner">
</div>
<h1>
    Shop now
</h1>
<div class="container">
    <div class="row">
        {% for product in page_obj %}
        <div class="col-md-4">
            <div class="card">
                <img src="{{ product.imagen.url }}" class="card-img-top" alt="{{ product.name }}" width="300px"
                     height="300px">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text">${{ product.price }}</p>
                    <a href="{% url 'add_to_order' product.id %}" class="btn btn-primary">Add to order</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li
                            class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>